data_source athena:
  type: duckdb
  database: /tmp/athena.duck
  read_only: true
  schema_name: public

soda_cloud:
  host: cloud.us.soda.io
  api_key_id: ${SODA_CLOUD_API_KEY_ID}
  api_key_secret: ${SODA_CLOUD_API_KEY_SECRET}
