# >>> Connect the Data Source
data_source athena:
  type: bigquery
  project_id: ${GCP_PROJECT}
  dataset: enrique_o_cool_dataset
  auth_scopes:
    - https://www.googleapis.com/auth/bigquery
    - https://www.googleapis.com/auth/cloud-platform
    - https://www.googleapis.com/auth/drive
  account_info_json_path: /opt/soda/etc/service_account.json

# >>> Discover Datasets
discover datasets:
  datasets:
    - include %

sample datasets:
  # Include all datasets except staging
  datasets:
    - include %
    - exclude stg%

# >>> Profile Datasets
profile columns:
  # Include all datasets except staging
  columns:
    - "%.%"
    - exclude stg%.%

# >>> Check Datasets
automated monitoring:
  # Exclude all datasets / Disable monitoring
  datasets:
    - exclude %
